# docker-compose -f db.compose.yaml up -d
version: "3.8"
services:
  dyploma-db:
    container_name: dyploma-db
    image: postgres:14
    environment:
      POSTGRES_DB: dyploma-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/dyploma_db/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G